apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cywell-opslens-operator
  labels:
    app.kubernetes.io/name: cywell-opslens
    app.kubernetes.io/component: operator-rbac
rules:
  - apiGroups:
      - opslens.cywell.io
    resources:
      - opslensinstallations
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - opslens.cywell.io
    resources:
      - opslensinstallations/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
      - persistentvolumeclaims
      - services
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
    verbs:
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - console.openshift.io
    resources:
      - consoleplugins
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - operator.openshift.io
    resources:
      - consoles
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ols.openshift.io
    resources:
      - olsconfigs
    verbs:
      - get
      - list
      - watch
      - update
      - patch
