apiVersion: v1
kind: ServiceAccount
metadata:
  name: cywell-opslens-operator
  namespace: cywell-opslens
  labels:
    app.kubernetes.io/name: cywell-opslens
    app.kubernetes.io/component: operator
